openapi: 3.0.0
info:
  title: "Express TODO RESTful api"
  version: "1.0.0"
  description: "This is a simple CRUD API application made with Express and documented with Swagger"
servers:
  - url: "http://localhost:8000/api/v1"
    description: "Development server"
paths:
  /:
    get:
      summary: "Hello endpoint"
      responses:
        200:
          description: "Returns: Hello World!"
